### ISSUE TITLE
关于几种跟踪算法的小白问题

### ISSUE THREAD

**Issue by 2436917927** [Naughty-Galileo/YoloV5_MCMOT#1]
您好，我第一次接触目标跟踪问题，请问ByteTrack是不是不需要训练，只需要获取检测器的检测框和置信度就可以完成跟踪，所以要在其他数据集上实现跟踪的话，是不是只要训练好检测器就可以；而DeepSort这类算法有自己的特征提取网络，是不是除了训练检测器还需要拿ReID数据集来训练DeepSort呢？

**Comment by Naughty-Galileo** [comment]
ByteTrack需要训练检测器，这与你想要跟踪的类别有关，如果没有数据并且类别是coco里的就用官方模型也行。
需要特征提取的跟踪器需要训练这部分网络，这部分训练我并没有提供 ，训练的话可以参考deepsort等官方实现

**Comment by 2436917927** [comment]
好的谢谢您，我这边有一个非coco类别的目标检测数据，主要是没有ReID数据集，所以想调研一些类似ByteTrack的不需要训练的跟踪器。那这边想再跟您确认一下，那我只要训练一个检测器比如说YOLOv7，然后把ByteTrack接在检测器后面就可以实现我这类数据的跟踪了是嘛？

**Comment by Naughty-Galileo** [comment]
是的 我采用的跟踪器是Yolov5，只要把检测结果按照一定格式传给跟踪器就行，具体参考可以参考detect_track实现，主要是检测框、置信度、类别一一对应 。bytetrack、sort、botsort都可以不训练reid模型
