### ISSUE TITLE
跟踪指标相关问题

### ISSUE THREAD

**Issue by eoozbq** [Naughty-Galileo/YoloV5_MCMOT#3]
您好，请问一下怎么获得不同跟踪模型的评价指标呢？

**Comment by Naughty-Galileo** [comment]
这个建议看一下mot的评价指标，实际上，这个项目并不是严格意义上的MOT.这是多类别的，目的是能够用来进行多类别的检测与跟踪，因此暂时没有对这种模型的评价指标。测试指标还是需要在MOT数据集上测试验证。

**Comment by 18914175218** [comment]
这个代码可以生成跟踪产生的txt，然后去做评估呢

**Comment by Naughty-Galileo** [comment]
> 这个代码可以生成跟踪产生的txt，然后去做评估呢

嗯嗯可以的哦 根据自己需要的格式生成txt
