### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by wangchao0720** [Naughty-Galileo/YoloV5_MCMOT#4]
hello博主，请问这份代码修改哪里就是调用摄像头检测了

**Comment by wangchao0720** [comment]
如果没有的话能不能加一下您的联系方式有些问题想请教您，我的vx    wang17393183227

**Comment by Naughty-Galileo** [comment]
得自己写个函数调用摄像头，然后不停向这个跟踪器传递照片，返回结果显示出来就能可视化

**Comment by wangchao0720** [comment]
好的谢谢博主
