### ISSUE TITLE
关于检测器的输出和追踪器的输入问题

### ISSUE THREAD

**Issue by DongChenwei2000** [Naughty-Galileo/YoloV5_MCMOT#5]
博主您好，我想进行多类别的追踪，想问下要输入到追踪器中的det具体是什么样的。我目前只知道前4位是bbox，后面三位应该是类别和置信度之类的，能否告诉我具体的输入呢

**Comment by Naughty-Galileo** [comment]
```python
 output_results = output_results.numpy()
confidences = output_results[:, 4]
bboxes = output_results[:, :4]  # x1y1x2y2
clss = output_results[:, 5]
```

**Comment by Naughty-Galileo** [comment]
> ```python
>  output_results = output_results.numpy()
> confidences = output_results[:, 4]
> bboxes = output_results[:, :4]  # x1y1x2y2
> clss = output_results[:, 5]
> ```

分别是boxx confidence clss
